kind: Pod
metadata:
apiVersion: v1
kind: Pod
metadata:
  name: configtest-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: LOGGING_STATE
          valueFrom:
            configMapKeyRef:
              name: logconfig
              key: LOG_LEVEL
  restartPolicy: Never
