apiVersion: v1
kind: Pod
metadata:
  name: cricketapp
  labels:
    name: cricketapp
spec:
  containers:
  - name: webtier
    image: nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
  - name: cachetier
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
