apiVersion: v1
kind: Secret
metadata:
  name: mydbcred
type: Opaque
stringData:
  dbpassword: Nilesh1234578
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mydbcred
                  key: dbpassword
        resources:
          limits:
            memory: "1256Mi"
            cpu: "1500m"
       ports:
        - containerPort: 3306
